spring.application.name=market-read-service
server.port=8082

#Mongo DB
spring.mongodb.uri=mongodb://root:1211@localhost:27017/market?authSource=admin

#Redis Cache
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379



