spring.application.name=price-write-service
server.port=8081

#Kafka
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.group-id=price-write-group

#MongoDB
spring.mongodb.uri=mongodb://root:1211@localhost:27017/market?authSource=admin
app.mongodb.collection=prices

#Redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
app.redis.price-ttl-seconds=30
